// The company data pack (data/seed/) is stored as JavaScript, not JSON, so the app can load it even when
// index.html is opened straight from the folder: browsers refuse to read .json files from a file:// page,
// but they do run <script> files. Each file is a single statement that queues one entry:
//
//   (globalThis.LSI_SEED = globalThis.LSI_SEED || []).push(["clients", [ …the records… ]]);
//
// The app (js/core/seed.js) loads each file with a <script> tag and takes its entry off the queue.
// The Node tools read the same files here WITHOUT running them: the part inside push( … ) is plain JSON.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const OPEN = '(globalThis.LSI_SEED = globalThis.LSI_SEED || []).push(';
const CLOSE = ');';

/** The text of a data-pack file holding `value` under `key` (a collection name, 'manifest' or 'validation-report'). */
export function seedFileText(key, value, comment = 'Landscapers Inc. HQ — company data pack (PRIVATE). Generated by tools/build-seed.js; do not edit by hand.') {
  return `/* ${comment} */\n${OPEN}${JSON.stringify([key, value])}${CLOSE}\n`;
}

/** Parse a data-pack file → { key, value }. Throws if the file is not in the expected form. */
export function parseSeedFile(text, where = 'data-pack file') {
  const start = text.indexOf(OPEN);
  const end = text.lastIndexOf(CLOSE);
  if (start < 0 || end < start) throw new Error(`${where} is not a data-pack file (expected ${OPEN}…${CLOSE})`);
  const entry = JSON.parse(text.slice(start + OPEN.length, end));
  if (!Array.isArray(entry) || entry.length !== 2 || typeof entry[0] !== 'string') throw new Error(`${where}: expected ["<key>", <value>]`);
  return { key: entry[0], value: entry[1] };
}

export function writeSeedFile(path, key, value, comment) { writeFileSync(path, seedFileText(key, value, comment)); }
export function readSeedFile(path, expectKey = null) {
  const { key, value } = parseSeedFile(readFileSync(path, 'utf8'), path);
  if (expectKey && key !== expectKey) throw new Error(`${path} holds "${key}", expected "${expectKey}"`);
  return value;
}

/** True when `dir` holds a data pack. */
export const hasPack = dir => existsSync(join(dir, 'manifest.js'));
/** The pack's manifest: { version, built_at, collections: [{ name, file, count, label }] } */
export const readManifest = dir => readSeedFile(join(dir, 'manifest.js'), 'manifest');
/** One collection's records (by name). */
export function readCollection(dir, name) {
  const file = join(dir, `${name}.js`);
  return existsSync(file) ? readSeedFile(file, name) : null;
}
/** The whole pack: { manifest, records: { <collection>: [rows] } } in manifest order. */
export function readPack(dir) {
  const manifest = readManifest(dir);
  const records = {};
  for (const c of manifest.collections) records[c.name] = readSeedFile(join(dir, c.file), c.name);
  return { manifest, records };
}
