/* =============================================================================
   The Supabase SQL for steps 01–05, generated from the app's schema (js/schema/*.js),
   so the browser (js/core/validate.js) and the database enforce the SAME rules.
   Plain functions that return the SQL text: Admin → Go live shows and downloads
   it, tools/gen-sql.js writes it to files, tools/test-sql.js runs it in Postgres.
   Never edit the SQL by hand — change the schema, and every copy follows.
   ========================================================================== */
import { SCHEMA, SYSTEM_FIELDS, AUDIT_EXEMPT } from '../core/schema.js';
import { ident } from './ident.js'; // quotes reserved words too (mail_messages.to must be written "to")

const q = s => `'${String(s).replace(/'/g, "''")}'`;
const header = title => `-- =============================================================================\n-- Landscapers Inc. HQ — ${title}\n-- GENERATED by js/sql/schema.js from js/schema/*.js — do not edit by hand.\n-- =============================================================================\n\n`;

function sqlType(f) {
  switch (f.type) {
    case 'int': return 'integer';
    case 'number': case 'percent': case 'rating': return 'double precision';
    case 'money': return f.precise ? 'numeric(16,6)' : 'numeric(14,2)';
    case 'date': return 'date';
    case 'datetime': return 'timestamptz';
    case 'bool': return 'boolean';
    case 'multi': case 'tags': case 'refs': case 'json': case 'files': return 'jsonb';
    default: return 'text';
  }
}
const optVals = f => (f.options || []).map(o => (typeof o === 'object' ? o.value : o));

/** 01 — every table, its constraints and indexes, and the role helper functions. */
export function schemaSql() {
  let s = header('schema (tables, constraints, indexes)');
  s += `create extension if not exists pgcrypto;\nset client_min_messages = warning; -- re-running: skip the "already exists" notices\n\n`;
  // The helper functions are appended AFTER the tables: PostgreSQL validates a SQL function's body when it is
  // created, so my_role() cannot be defined before public.profiles exists.
  const HELPERS = `-- Role of the signed-in user (from public.profiles). SECURITY DEFINER so policies can call it.
create or replace function public.my_role() returns text language sql stable security definer set search_path = public as $$
  select role from public.profiles where id = auth.uid()::text and deleted_at is null and coalesce(status,'active') = 'active'
$$;
create or replace function public.has_role(roles text[]) returns boolean language sql stable security definer set search_path = public as $$
  select coalesce(public.my_role() = any(roles) or public.my_role() in ('owner','admin'), false)
$$;
create or replace function public.my_name() returns text language sql stable security definer set search_path = public as $$
  select name from public.profiles where id = auth.uid()::text
$$;
-- May the signed-in user open this shared drive? A restricted drive (FINANCE, HR) is open to owner/admin/manager,
-- the roles listed on the drive and its members. Runs as the caller, so the drives table's own policy applies.
create or replace function public.can_see_drive(d_id text) returns boolean language sql stable set search_path = public as $$
  select d_id is null or not exists (
    select 1 from public.drives d
    where d.id = d_id and coalesce(d.restricted, false)
      and not (public.has_role(array['manager'])
        or (jsonb_typeof(d.roles) = 'array' and public.my_role() in (select jsonb_array_elements_text(d.roles)))
        or (jsonb_typeof(d.members) = 'array' and exists (select 1 from jsonb_array_elements(d.members) m where coalesce(m->>'profile_id', m->>'user_id') = auth.uid()::text))))
$$;\n\n`;

  for (const [col, def] of Object.entries(SCHEMA)) {
    const cols = [
      `  id text primary key default gen_random_uuid()::text`,
      `  created_at timestamptz not null default now()`, `  created_by text`, `  created_by_name text`,
      `  updated_at timestamptz not null default now()`, `  updated_by text`, `  updated_by_name text`,
      `  deleted_at timestamptz`, `  deleted_by text`, `  deleted_by_name text`,
      `  _src text`, `  _seed boolean not null default false`,
      `  data jsonb not null default '{}'::jsonb`
    ];
    const checks = [];
    for (const [name, f] of Object.entries(def.fields)) {
      if (f.computed || SYSTEM_FIELDS.includes(name)) continue;
      let line = `  ${ident(name)} ${sqlType(f)}`;
      if (f.default !== undefined && typeof f.default !== 'function' && !['json', 'refs', 'tags', 'multi'].includes(f.type)) line += ` default ${typeof f.default === 'boolean' ? f.default : typeof f.default === 'number' ? f.default : q(f.default)}`;
      cols.push(line);
      const c = ident(name);
      if (f.type === 'enum' && optVals(f).length) checks.push(`check (${c} is null or ${c} in (${optVals(f).map(q).join(', ')}))`);
      if (['int', 'number', 'money', 'percent', 'rating'].includes(f.type)) {
        if (f.min != null) checks.push(`check (${c} is null or ${c} >= ${f.min})`);
        if (f.max != null) checks.push(`check (${c} is null or ${c} <= ${f.max})`);
        if (f.type === 'percent' && f.min == null) checks.push(`check (${c} is null or (${c} >= 0 and ${c} <= 100))`);
      }
      if (f.type === 'email' && f.strict !== false) checks.push(`check (${c} is null or ${c} ~* '^[^@\\s]+@[^@\\s]+\\.[a-z]{2,}$')`);
      if (f.type === 'time') checks.push(`check (${c} is null or ${c} ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$')`);
      if (f.type === 'sa_id' && f.strict !== false) checks.push(`check (${c} is null or ${c} ~ '^[0-9]{13}$')`);
      if (f.type === 'company_reg') checks.push(`check (${c} is null or ${c} ~ '^[0-9]{4}/[0-9]{6}/[0-9]{2}$')`);
      if (f.type === 'branch_code') checks.push(`check (${c} is null or ${c} ~ '^[0-9]{6}$')`);
      if (f.required && f.dbRequired !== false) checks.push(`check (deleted_at is not null or ${c} is not null)`);
    }
    s += `-- ${def.label}\ncreate table if not exists public.${ident(col)} (\n${cols.join(',\n')}${checks.length ? ',\n  ' + checks.join(',\n  ') : ''}\n);\n`;
    // upgrading an existing database: fields added in a later release become columns (never dropped, data kept)
    s += cols.slice(1).map(l => `alter table public.${ident(col)} add column if not exists ${l.trim()};\n`).join('');
    for (const [name, f] of Object.entries(def.fields)) {
      if (f.type === 'ref' || ['date'].includes(f.type) || f.unique || /(_id|status|date)$/.test(name)) s += `create index if not exists ${col}_${name}_idx on public.${ident(col)} (${ident(name)});\n`;
      if (f.unique) s += `create unique index if not exists ${col}_${name}_uniq on public.${ident(col)} (lower(${ident(name)}::text)) where deleted_at is null and ${ident(name)} is not null;\n`;
    }
    s += `\n`;
  }
  s += HELPERS;
  return s;

}

/** 02 — Row Level Security on every table (who may read and change what), sensitive-column views. */
export function rlsSql() {
  const roleExpr = list => {
    if (list === '*' || (Array.isArray(list) && list.includes('*'))) return `auth.uid() is not null and public.my_role() is not null`;
    if (!list || !list.length) return `public.has_role(array[]::text[])`;
    return `public.has_role(array[${list.map(q).join(', ')}])`;
  };
  let r = header('Row Level Security');
  r += `-- Every table: RLS enabled; anon has no access at all.\n-- Owner/admin pass every check through public.has_role().\n\n`;
  const OWN_ROWS = { notifications: 'user_id', mail_flags: 'user_id', chat_reads: 'user_id', ai_conversations: 'user_id' };
  for (const [col, def] of Object.entries(SCHEMA)) {
    const t = `public.${ident(col)}`;
    const p = def.perms || { read: '*', write: [], delete: [] };
    // ENABLE (not FORCE): API users (anon/authenticated) are always bound by RLS; the table owner is
    // not, which lets the SECURITY DEFINER audit/attribution functions write the audit log.
    r += `alter table ${t} enable row level security;\nrevoke all on ${t} from anon;\ngrant select, insert, update, delete on ${t} to authenticated;\n`;
    for (const act of ['select', 'insert', 'update', 'delete']) r += `drop policy if exists ${col}_${act} on ${t};\n`;
    if (OWN_ROWS[col]) {
      const k = OWN_ROWS[col];
      r += `create policy ${col}_select on ${t} for select to authenticated using (${k} = auth.uid()::text or public.has_role(array[]::text[]));\n`;
      r += `create policy ${col}_insert on ${t} for insert to authenticated with check (auth.uid() is not null);\n`;
      r += `create policy ${col}_update on ${t} for update to authenticated using (${k} = auth.uid()::text) with check (${k} = auth.uid()::text);\n`;
      r += `create policy ${col}_delete on ${t} for delete to authenticated using (${k} = auth.uid()::text or public.has_role(array[]::text[]));\n\n`;
      continue;
    }
    let readUsing = roleExpr(p.read);
    if (col === 'notes') readUsing = `(${readUsing}) and (coalesce(shared, true) or created_by = auth.uid()::text)`;
    if (col === 'events') readUsing = `(${readUsing}) and (coalesce(visibility,'company') <> 'private' or created_by = auth.uid()::text or attendees ? auth.uid()::text)`;
    if (col === 'chat_channels') readUsing = `(${readUsing}) and (not coalesce(private,false) or members ? auth.uid()::text or created_by = auth.uid()::text)`;
    if (col === 'chat_messages') readUsing = `(${readUsing}) and exists (select 1 from public.chat_channels c where c.id = channel_id and (not coalesce(c.private,false) or c.members ? auth.uid()::text or c.created_by = auth.uid()::text))`;
    if (col === 'mail_messages') readUsing = `(${readUsing}) and (from_user_id = auth.uid()::text or ${ident('to')}::text like '%' || auth.uid()::text || '%' or cc::text like '%' || auth.uid()::text || '%' or bcc::text like '%' || auth.uid()::text || '%' or public.has_role(array[]::text[]))`;
    if (col === 'profiles') {
      r += `create policy profiles_select on ${t} for select to authenticated using (auth.uid() is not null);\n`;
      r += `create policy profiles_insert on ${t} for insert to authenticated with check (public.has_role(array[]::text[]));\n`;
      r += `create policy profiles_update on ${t} for update to authenticated using (id = auth.uid()::text or public.has_role(array[]::text[])) with check (id = auth.uid()::text or public.has_role(array[]::text[]));\n`;
      r += `create policy profiles_delete on ${t} for delete to authenticated using (public.has_role(array['owner']));\n`;
      r += `-- People may edit their own profile but never their own role or status (enforced by trigger in 03_triggers.sql).\n\n`;
      continue;
    }
    // Row-level limits that apply to every action, not just reading (a row you may not see you may not change either).
    let rowLimit = null;
    // sheets built from restricted records (payroll, budgets…) stay with the roles that may read those records
    if (col === 'sheets') rowLimit = `(restricted_to is null or jsonb_typeof(restricted_to) <> 'array' or jsonb_array_length(restricted_to) = 0 or created_by = auth.uid()::text or public.my_role() in (select jsonb_array_elements_text(restricted_to)) or public.has_role(array[]::text[]))`;
    // HR and incident form responses are confidential: the person who submitted, plus the roles that handle them
    if (col === 'form_responses') rowLimit = `(coalesce(form_category, '') not in ('hr', 'incident') or created_by = auth.uid()::text or (form_category = 'hr' and public.has_role(array['manager','hr'])) or (form_category = 'incident' and public.has_role(array['manager','hr','operations'])))`;
    // files and folders in a restricted shared drive (FINANCE, HR) stay with the people who may open that drive;
    // confidential files additionally with manager/HR (and whoever uploaded them)
    if (col === 'files') rowLimit = `((not coalesce(confidential,false) or public.has_role(array['manager','hr']) or created_by = auth.uid()::text) and public.can_see_drive(drive_id))`;
    if (col === 'folders') rowLimit = `public.can_see_drive(drive_id)`;
    const lim = x => (rowLimit ? `(${x}) and ${rowLimit}` : x);
    r += `create policy ${col}_select on ${t} for select to authenticated using (${lim(readUsing)});\n`;
    r += `create policy ${col}_insert on ${t} for insert to authenticated with check (${lim(roleExpr(p.write))});\n`;
    // 'update' follows 'write' unless the collection sets it (form responses: anyone submits, reviewers change)
    const ownEdit = !p.update && ['events', 'tasks', 'notes', 'comments', 'chat_messages', 'mail_messages', 'files', 'folders', 'docs', 'sheets', 'slides'].includes(col);
    const upd = `${roleExpr(p.update || p.write)}${ownEdit ? ' or created_by = auth.uid()::text' : ''}`;
    r += `create policy ${col}_update on ${t} for update to authenticated using (${lim(upd)}) with check (${lim(upd)});\n`;
    r += `create policy ${col}_delete on ${t} for delete to authenticated using (${lim(roleExpr(p.delete))});\n`;
    // Sensitive columns: nobody can SELECT them from the table through the API (column privileges); the roles
    // allowed to see them read them through public.<col>_sensitive, whose WHERE clause checks the role.
    // Writes are unchanged (the row policies above decide who may insert/update).
    const sens = Object.entries(def.fields).filter(([, f]) => f.sensitive && !f.computed).map(([n]) => n);
    if (sens.length) {
      const allowedRoles = def.sensitiveRoles || ['manager', 'finance'];
      const visible = [...SYSTEM_FIELDS, 'data', ...Object.keys(def.fields).filter(n => !def.fields[n].computed && !SYSTEM_FIELDS.includes(n) && !sens.includes(n))];
      r += `-- Sensitive columns (${sens.join(', ')}) are only returned to owner, admin, ${allowedRoles.join(', ')}: they are left out of the\n`;
      r += `-- column grant below and served by the view public.${col}_sensitive (row filter on the role).\n`;
      r += `revoke select on ${t} from authenticated;\n`;
      r += `grant select (${visible.map(ident).join(', ')}) on ${t} to authenticated;\n`;
      r += `create or replace view public.${ident(`${col}_sensitive`)} with (security_barrier = true) as\n  select id, ${sens.map(ident).join(', ')} from ${t} where public.has_role(array[${allowedRoles.map(q).join(', ')}]);\n`;
      r += `revoke all on public.${ident(`${col}_sensitive`)} from public, anon;\ngrant select on public.${ident(`${col}_sensitive`)} to authenticated;\n`;
    }
    r += `\n`;
  }
  r += `-- audit_log is append-only for everyone (written by trigger only)\nrevoke insert, update, delete on public.audit_log from authenticated;\n`;
  return r;

}

/** 03 — who/when stamping, the append-only audit log, profile protection, form-response categories. */
export function triggersSql() {
  let tr = header('triggers: attribution (who/when), audit log, protected columns');
  tr += `-- Stamp created_by / updated_by from the JWT so nobody can pretend to be someone else.
create or replace function public.stamp_attribution() returns trigger language plpgsql security definer set search_path = public as $$
declare uid text := auth.uid()::text; uname text := public.my_name();
begin
  if tg_op = 'INSERT' then
    if uid is not null then new.created_by := uid; new.created_by_name := coalesce(uname, new.created_by_name); end if;
    new.created_at := coalesce(new.created_at, now());
  else
    new.created_by := old.created_by; new.created_by_name := old.created_by_name; new.created_at := old.created_at;
  end if;
  if uid is not null then new.updated_by := uid; new.updated_by_name := coalesce(uname, new.updated_by_name); end if;
  new.updated_at := now();
  return new;
end $$;

-- Append-only audit log with a field-level diff.
create or replace function public.write_audit() returns trigger language plpgsql security definer set search_path = public as $$
declare d jsonb := '{}'::jsonb; k text; o jsonb; n jsonb; act text; rec jsonb;
begin
  if tg_op = 'INSERT' then act := 'create'; rec := to_jsonb(new);
  elsif tg_op = 'DELETE' then act := 'purge'; rec := to_jsonb(old);
  else
    rec := to_jsonb(new); o := to_jsonb(old); n := to_jsonb(new);
    act := case when (o->>'deleted_at') is null and (n->>'deleted_at') is not null then 'delete' when (o->>'deleted_at') is not null and (n->>'deleted_at') is null then 'restore' else 'update' end;
    for k in select jsonb_object_keys(n) loop
      if k not in ('updated_at','updated_by','updated_by_name') and (o->k) is distinct from (n->k) then d := d || jsonb_build_object(k, jsonb_build_array(o->k, n->k)); end if;
    end loop;
    if d = '{}'::jsonb then return new; end if;
  end if;
  insert into public.audit_log (id, at, user_id, user_name, action, collection, record_id, label, changes, created_by, created_by_name)
  values (gen_random_uuid()::text, now(), auth.uid()::text, coalesce(public.my_name(), 'System'), act, tg_table_name, rec->>'id',
          coalesce(rec->>'name', rec->>'title', rec->>'subject', rec->>'number', rec->>'code', rec->>'id'), case when act = 'update' then d else null end,
          auth.uid()::text, public.my_name());
  return coalesce(new, old);
end $$;

-- Nobody can change their own role or status; only owner/admin can change roles.
create or replace function public.protect_profile() returns trigger language plpgsql security definer set search_path = public as $$
begin
  if (new.role is distinct from old.role or new.status is distinct from old.status) and not public.has_role(array[]::text[]) then
    raise exception 'Only an administrator can change roles or account status';
  end if;
  if new.role = 'owner' and old.role <> 'owner' and public.my_role() <> 'owner' then raise exception 'Only the owner can appoint another owner'; end if;
  return new;
end $$;

-- A response's category always comes from its form, never from the person submitting it:
-- it decides who may read HR and incident responses (see form_responses policies in 02_rls.sql).
create or replace function public.form_response_category() returns trigger language plpgsql security definer set search_path = public as $$
begin
  new.form_category := (select f.category from public.forms f where f.id = new.form_id);
  return new;
end $$;
-- …and follows the form if the form is later re-categorised.
create or replace function public.form_category_cascade() returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.category is distinct from old.category then
    update public.form_responses set form_category = new.category where form_id = new.id;
  end if;
  return new;
end $$;

`;
  for (const col of Object.keys(SCHEMA)) {
    const t = `public.${ident(col)}`;
    tr += `drop trigger if exists ${col}_stamp on ${t};\ncreate trigger ${col}_stamp before insert or update on ${t} for each row execute function public.stamp_attribution();\n`;
    if (!AUDIT_EXEMPT.has(col) && SCHEMA[col].audit !== false) tr += `drop trigger if exists ${col}_audit on ${t};\ncreate trigger ${col}_audit after insert or update or delete on ${t} for each row execute function public.write_audit();\n`;
  }
  tr += `drop trigger if exists profiles_protect on public.profiles;\ncreate trigger profiles_protect before update on public.profiles for each row execute function public.protect_profile();\n`;
  tr += `drop trigger if exists form_responses_category on public.form_responses;\ncreate trigger form_responses_category before insert or update of form_id, form_category on public.form_responses for each row execute function public.form_response_category();\n`;
  tr += `drop trigger if exists forms_category_cascade on public.forms;\ncreate trigger forms_category_cascade after update of category on public.forms for each row execute function public.form_category_cascade();\n`;
  return tr;

}

/** 04 — the private drive and avatars storage buckets and their access rules. */
export function storageSql() {
  let st = header('storage buckets + policies');
  st += `insert into storage.buckets (id, name, public, file_size_limit) values ('drive', 'drive', false, 52428800) on conflict (id) do nothing;
insert into storage.buckets (id, name, public, file_size_limit) values ('avatars', 'avatars', false, 5242880) on conflict (id) do nothing;

drop policy if exists drive_read on storage.objects;
drop policy if exists drive_write on storage.objects;
drop policy if exists drive_update on storage.objects;
drop policy if exists drive_delete on storage.objects;
-- A stored document is readable only by people who can see its record in public.files (the files policy — confidential
-- flag, restricted drives — applies inside this check) or who uploaded it. Profile pictures are readable by all staff.
create policy drive_read   on storage.objects for select to authenticated using (public.my_role() is not null and (
  bucket_id = 'avatars' or (bucket_id = 'drive' and (owner = auth.uid() or exists (select 1 from public.files f where f.storage_path = storage.objects.name)))));
-- uploads go to "<drive id>/<file id>/<name>": nobody writes into a restricted drive they cannot open
create policy drive_write  on storage.objects for insert to authenticated with check (bucket_id in ('drive','avatars') and public.my_role() is not null and public.my_role() <> 'viewer'
  and (bucket_id = 'avatars' or public.can_see_drive(split_part(name, '/', 1))));
create index if not exists files_storage_path_idx on public.files (storage_path);
create policy drive_update on storage.objects for update to authenticated using (bucket_id in ('drive','avatars') and (owner = auth.uid() or public.has_role(array['manager'])));
create policy drive_delete on storage.objects for delete to authenticated using (bucket_id in ('drive','avatars') and (owner = auth.uid() or public.has_role(array['manager'])));
`;
  return st;

}

/** 05 — live updates on every phone and PC. */
export function realtimeSql() {
  let rt = header('realtime (live updates on every phone and PC)');
  rt += `do $$ begin\n  if not exists (select 1 from pg_publication where pubname = 'supabase_realtime') then create publication supabase_realtime; end if;\nend $$;\n`;
  for (const col of Object.keys(SCHEMA)) if (col !== 'audit_log') rt += `do $$ begin alter publication supabase_realtime add table public.${ident(col)}; exception when duplicate_object then null; end $$;\n`;
  return rt;


}
