/* =============================================================================
   Step 06 — the company data: every record of the data pack as SQL, loaded in
   one transaction. Built on demand from the pack (Admin → Go live reads it with
   loadPack(); tools__gen-sql.js and tools__test-sql.js with tools__lib__seed-files.js)
   — the SQL holds private company data, so it is never kept in the project.
   ========================================================================== */
import { SCHEMA, SYSTEM_FIELDS } from '../core/schema.js';
import { ident } from './ident.js';

const sqlVal = v => (v === null || v === undefined ? 'null' : typeof v === 'number' ? (Number.isFinite(v) ? String(v) : 'null') : typeof v === 'boolean' ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
// Local-mode password fields never go to Supabase: logins there are Supabase Auth accounts (step 08 links them),
// and every signed-in user can read profiles.
const SUPABASE_OMIT = { profiles: new Set(['password_hash', 'password_salt']) };

/** The step 06 SQL for a data pack: { manifest, records: { <collection>: [rows] } } (rows as the pack stores them). */
export function seedSql({ manifest, records }) {
  let sql = `-- Landscapers Inc. HQ — company data seed (GENERATED by js__sql__seed.js from the data pack, version ${manifest.version})\n-- Run AFTER 01–05. Safe to re-run: existing ids are updated only while they are still untouched seed rows.\nbegin;\n` +
    // skip attribution/audit triggers during the bulk load; if the project does not allow it the load still works
    // (the attribution trigger keeps the imported created_by values when there is no signed-in user)
    `do $$ begin set local session_replication_role = replica; exception when others then raise notice 'triggers stay on during the seed load: %', sqlerrm; end $$;\n`;
  for (const [col, rows] of Object.entries(records).sort()) {
    const def = SCHEMA[col];
    if (!def) throw new Error(`The data pack has a collection the app does not know: ${col}`);
    const cols = new Set([...SYSTEM_FIELDS, ...Object.keys(def.fields).filter(k => !def.fields[k].computed)]);
    const omit = SUPABASE_OMIT[col] || new Set();
    for (const r of rows) {
      const known = {}, data = {};
      for (const [k, v] of Object.entries(r)) { if (omit.has(k)) continue; (cols.has(k) ? (known[k] = v) : (data[k] = v)); }
      const keys = Object.keys(known);
      const vals = keys.map(k => {
        const f = def.fields[k];
        const v = known[k];
        if (f && ['json', 'refs', 'tags', 'multi', 'files'].includes(f.type)) return v == null ? 'null' : `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
        if (v !== null && typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'`;
        return sqlVal(v);
      });
      keys.push('data'); vals.push(`'${JSON.stringify(data).replace(/'/g, "''")}'::jsonb`);
      sql += `insert into public.${ident(col)} (${keys.map(ident).join(', ')}) values (${vals.join(', ')}) on conflict (id) do update set ${keys.filter(k => k !== 'id').map(k => `${ident(k)} = excluded.${ident(k)}`).join(', ')} where public.${ident(col)}._seed and public.${ident(col)}.updated_by is not distinct from public.${ident(col)}.created_by;\n`;
    }
  }
  sql += `commit;\n-- Verification\nselect '${manifest.version}' as seed_version${Object.entries(records).sort().map(([c, rows]) => `, (select count(*) from public.${ident(c)} where _seed) = ${rows.length} as ${c}_ok`).join('')};\n`;
  return sql;
}
