// Build js__app.bundle.js — the whole app as ONE ordinary script, for when index.html is opened by
// double-clicking it (file://). Browsers refuse to load ES modules from local files, so js__boot.js runs this
// file there instead of js__main.js. Served over http(s) the modules in js/ load directly and the bundle is not used.
//
//   npm run build                  (node tools__build.js)  — run after changing anything in js/
//   node tools__build.js --check    exit 1 if js__app.bundle.js is out of date (npm run check does this too)
//   node tools__build.js --logo     also rewrite js__core__logo.js from assets__landscapers-logo.jpg
//
// Uses esbuild-wasm (npm install): plain JavaScript, so it runs anywhere Node does.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export const BUNDLE = 'js__app.bundle.js';
const HEADER = `/* Landscapers Inc. HQ - the whole app in one script, for index.html opened straight from the folder (file://)
   GENERATED by tools__build.js from js/ - do not edit; change js/ and run "npm run build". js__boot.js decides which version runs. */`;

/** The bundle text as it should be now (nothing is written). */
export async function bundleText() {
  const esbuild = await import('esbuild-wasm');
  const r = await esbuild.build({
    entryPoints: ['js__main.js'], absWorkingDir: root, bundle: true, format: 'iife', write: false,
    legalComments: 'none', logLevel: 'silent', banner: { js: HEADER }
  });
  if (r.errors.length) throw new Error(r.errors.map(e => e.text).join('\n'));
  return r.outputFiles[0].text;
}

/** js__core__logo.js as it should be for the current assets__landscapers-logo.jpg. */
export function logoModuleText() {
  const lines = readFileSync(join(root, 'assets__landscapers-logo.jpg')).toString('base64').match(/.{1,120}/g);
  return `/* The company logo (assets__landscapers-logo.jpg) as a data URL, for the PDFs the app draws (invoices,
   quotes, statements, slide decks). Built in rather than fetched, because a page opened straight from the
   folder (file://) cannot read its own files with fetch(). tools__check.js confirms it still matches the
   image in assets/ — after replacing the logo there, regenerate this file with:  node tools__build.js --logo */
export const LOGO_DATA_URL = 'data:image/jpeg;base64,' +
${lines.map(l => `  '${l}'`).join(' +\n')};
`;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes('--check');
  if (process.argv.includes('--logo')) { writeFileSync(join(root, 'js__core__logo.js'), logoModuleText()); console.log('✓ js__core__logo.js'); }
  let text;
  try { text = await bundleText(); }
  catch (e) {
    if (/Cannot find (package|module) 'esbuild-wasm'/.test(String(e))) { console.error('✗ esbuild-wasm is not installed — run "npm install" in this folder first.'); process.exit(1); }
    throw e;
  }
  const file = join(root, BUNDLE);
  const current = existsSync(file) ? readFileSync(file, 'utf8') : null;
  if (check) {
    if (current === text) { console.log(`✓ ${BUNDLE} is up to date`); process.exit(0); }
    console.error(`✗ ${BUNDLE} is out of date — run "npm run build"`); process.exit(1);
  }
  if (current === text) console.log(`✓ ${BUNDLE} already up to date (${(text.length / 1024).toFixed(0)} KB)`);
  else { writeFileSync(file, text); console.log(`✓ wrote ${BUNDLE} (${(text.length / 1024).toFixed(0)} KB)`); }
}
